# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml

jenkins:
  PipelineSecrets:

    # lets enable ECR docker builds
    DockerConfig: |-
      {
	    "credsStore": "ecr-login"
      }
