# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml

docker-registry:
  enabled: false

nexus:
  enabled: true
  image:
    repository: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x-nexus
    tag: 0.0.19
  persistence:
    storageClass: "alicloud-disk-available"
    size: 20Gi

chartmuseum:
  image:
    repository: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x-chartmuseum
    tag: v0.7.1
  persistence:
    storageClass: "alicloud-disk-available"
    size: 20Gi

jenkins:
  Master:
    Image: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x 
    ImageTag: 0.0.41
    ServiceType: LoadBalancer
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "registry.cn-beijing.aliyuncs.com"
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: registry.cn-beijing.aliyuncs.com/haoshuwei/jenkins-x-builder-maven:0.1.185 
  Persistence:
    StorageClass: "alicloud-disk-available"
    Size: 40Gi

monocular:
  enabled: false
heapster:
  image:
    repository: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x-heapster
    tag: v1.3.0
  resizer:
    image:
      repository: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x-heapster-addon-resizer
      tag: 1.7

jx:
  image:
    repository: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-x-jx
    tag: 1.3.717
