# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml

PipelineSecrets:

  # lets enable ACR docker builds
  DockerConfig: |-
    {
      "credsStore": "acr-linux"
    }
    
docker-registry:
  enabled: false    
