# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml

jenkins:
  Agent:
    # for PKS there is a different docker host path
    DockerHostPath: "/var/vcap/sys/run/docker/docker.sock"
    DockerMountPath: "/var/run/docker.sock"
