# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml
chartmuseum:
  enabled: true
  image:
    tag: v0.7.1
  env:
    open:
      AUTH_ANONYMOUS_GET: true
      DISABLE_API: false
      STORAGE: google
      STORAGE_GOOGLE_BUCKET: jenkinsx-chartmuseum
      STORAGE_GOOGLE_PREFIX: charts
  gcp:
    secret:
      enabled: true
      name: gcs-jenkinsx-chartmuseum
      key: gcs-chartmuseum.key.json

monocular:
  api:
    livenessProbe:
      initialDelaySeconds: 1000

jenkins:
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: jenkinsxio/builder-maven:latest
        volumes:
        - type: Secret
          secretName: jenkins-maven-settings
          mountPath: /root/.m2/
        - type: Secret
          secretName: jenkins-docker-cfg
          mountPath: /home/jenkins/.docker
      Nodejs:
        Containers:
          Nodejs:
            Image: jenkinsxio/builder-nodejs:latest
      Go:
        Containers:
          Go:
            Image: jenkinsxio/builder-go:latest

nexus:
  persistence:
    size: 100Gi
