# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/values.yaml
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: "registry.ng.bluemix.net"
# Smaller cluster configurations require more time   
jenkins:
  Master:
    Readiness:
      InitialDelaySeconds: 600
    Liveness:
      InitialDelaySeconds: 660